export const FETCH_POSTS_SUCCESS = 'FETCH_QUIZES_SUCCESS';

export const FETCH_POST_ITEM_SUCCESS = 'FETCH_POST_ITEM_SUCCESS';

export const CREATE_POST_TITLE = 'CREATE_POST_TITLE';
export const CREATE_POST_CONTENT = 'CREATE_POST_CONTENT';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_DISABLE_BUTTON = 'CREATE_POST_DISABLE_BUTTON';
